name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v5
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: "26"
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
