/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthedRoutesRouteRouteImport } from './routes/_authedRoutes/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VenuesIndexRouteImport } from './routes/venues/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as VenuesVenueIdIndexRouteImport } from './routes/venues/$venueId/index'
import { Route as AuthedRoutesProfileIndexRouteImport } from './routes/_authedRoutes/profile/index'
import { Route as VenuesVenueIdBookIndexRouteImport } from './routes/venues/$venueId/book/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoutesRouteRoute = AuthedRoutesRouteRouteImport.update({
  id: '/_authedRoutes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesIndexRoute = VenuesIndexRouteImport.update({
  id: '/venues/',
  path: '/venues/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const VenuesVenueIdIndexRoute = VenuesVenueIdIndexRouteImport.update({
  id: '/venues/$venueId/',
  path: '/venues/$venueId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoutesProfileIndexRoute =
  AuthedRoutesProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthedRoutesRouteRoute,
  } as any)
const VenuesVenueIdBookIndexRoute = VenuesVenueIdBookIndexRouteImport.update({
  id: '/venues/$venueId/book/',
  path: '/venues/$venueId/book/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/venues/': typeof VenuesIndexRoute
  '/profile/': typeof AuthedRoutesProfileIndexRoute
  '/venues/$venueId/': typeof VenuesVenueIdIndexRoute
  '/venues/$venueId/book/': typeof VenuesVenueIdBookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/venues': typeof VenuesIndexRoute
  '/profile': typeof AuthedRoutesProfileIndexRoute
  '/venues/$venueId': typeof VenuesVenueIdIndexRoute
  '/venues/$venueId/book': typeof VenuesVenueIdBookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authedRoutes': typeof AuthedRoutesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/venues/': typeof VenuesIndexRoute
  '/_authedRoutes/profile/': typeof AuthedRoutesProfileIndexRoute
  '/venues/$venueId/': typeof VenuesVenueIdIndexRoute
  '/venues/$venueId/book/': typeof VenuesVenueIdBookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/venues/'
    | '/profile/'
    | '/venues/$venueId/'
    | '/venues/$venueId/book/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/venues'
    | '/profile'
    | '/venues/$venueId'
    | '/venues/$venueId/book'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authedRoutes'
    | '/about'
    | '/_auth/login'
    | '/_auth/register'
    | '/venues/'
    | '/_authedRoutes/profile/'
    | '/venues/$venueId/'
    | '/venues/$venueId/book/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthedRoutesRouteRoute: typeof AuthedRoutesRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  VenuesIndexRoute: typeof VenuesIndexRoute
  VenuesVenueIdIndexRoute: typeof VenuesVenueIdIndexRoute
  VenuesVenueIdBookIndexRoute: typeof VenuesVenueIdBookIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authedRoutes': {
      id: '/_authedRoutes'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRoutesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/': {
      id: '/venues/'
      path: '/venues'
      fullPath: '/venues/'
      preLoaderRoute: typeof VenuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/venues/$venueId/': {
      id: '/venues/$venueId/'
      path: '/venues/$venueId'
      fullPath: '/venues/$venueId/'
      preLoaderRoute: typeof VenuesVenueIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authedRoutes/profile/': {
      id: '/_authedRoutes/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthedRoutesProfileIndexRouteImport
      parentRoute: typeof AuthedRoutesRouteRoute
    }
    '/venues/$venueId/book/': {
      id: '/venues/$venueId/book/'
      path: '/venues/$venueId/book'
      fullPath: '/venues/$venueId/book/'
      preLoaderRoute: typeof VenuesVenueIdBookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthedRoutesRouteRouteChildren {
  AuthedRoutesProfileIndexRoute: typeof AuthedRoutesProfileIndexRoute
}

const AuthedRoutesRouteRouteChildren: AuthedRoutesRouteRouteChildren = {
  AuthedRoutesProfileIndexRoute: AuthedRoutesProfileIndexRoute,
}

const AuthedRoutesRouteRouteWithChildren =
  AuthedRoutesRouteRoute._addFileChildren(AuthedRoutesRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthedRoutesRouteRoute: AuthedRoutesRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  VenuesIndexRoute: VenuesIndexRoute,
  VenuesVenueIdIndexRoute: VenuesVenueIdIndexRoute,
  VenuesVenueIdBookIndexRoute: VenuesVenueIdBookIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
